### PR TITLE
Fix Windows Deployment

### LINKED ISSUE #48: Problems with the Automated deploy
### Summary

Using the automated deploy script to deploy and running into this issue - deployment fails with this error - spawnSync sfdx ENOENT

### Steps To Reproduce:

1.  Installed all the prerequisites - VS code / git / sfdx / heroku cli 
2.  Executed the automated deployment instructions - node scripts/ecarsDeploy.js
3.  The script executes the - scratch org is setup successfully - when deploying to Scratch org-
after this result -  *** Pushing source to scratch org
4. Error is seen - spawnSync sfdx ENOENT

unable to install and use the sample on the scratch org. 

Please let me know for questions.

### PR DESCRIPTION
**Pull request by julianduque**
### What does this PR do?

Fix Windows Deployment when provisioning database in one of the Heroku Apps and properly copies the PDF Generation Images on Windows

### What issues does this PR fix or reference?

Fixes #48 

## The PR fulfills these requirements:

[ ] Tests for the proposed changes have been added/updated.
[ ] Code linting and formatting was performed.

### Functionality Before

Error while deploying Realtime Heroku App

### Functionality After

Finishes Deployment

### CODE REVIEW

**Comment by julianduque** [comment]
@pozil running `npm run prettier:verify` works locally but it is failing on the CI, any idea why?

**Comment by pozil** [comment]
@julianduque can you double check that you have the up to date prettier and plugin installed in your local project?

**Review by pozil — APPROVED** [review]
Looking good, thanks for fixing this issue.

**Review by pozil — APPROVED** [review]
Looking good, thanks for fixing this issue.

**Pull request merged**
